[www]
user  = www-data
group = www-data
listen = PHP_PORT
listen.owner = www-data
listen.group = www-data
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
clear_env = no



listen=wordpress:9000

# copier la base du conf php en modifiant juste les lignes listen et env, puisque le dockerfile prendra cette version pour remplacer le binaire. 
# Modifying lines about port and env in the php conf file
RUN sed -i -e 's/listen =.*/listen = wordpress:9000/g' /etc/php/7.3/fpm/pool.d/www.conf
	&& sed -i -e 's/;clear_env = no/clear_env = no/g' /etc/php/7.3/fpm/pool.d/www.conf